export const GET_ALL_BOOK = 'GET_ALL_BOOK';
export const GET_ALL_BOOK_SUCCESS = 'GET_ALL_BOOK_SUCCESS'; 
export const GET_ALL_BOOK_FAILED = 'GET_ALL_BOOK_FAILED'; 

export const INCREMENT_MAX_RESULT = 'INCREMENT_MAX_RESULT';
export const GET_MORE_BOOK = 'GET_MORE_BOOK';
export const GET_MORE_BOOK_SUCCESS = 'GET_MORE_BOOK_SUCCESS'; 
export const GET_MORE_BOOK_FAILED = 'GET_MORE_BOOK_FAILED'; 

export const MAKE_LIKE_BOOK = 'MAKE_LIKE_BOOK' 
export const MAKE_UNLIKE_BOOK = 'MAKE_UNLIKE_BOOK' 

export const DO_SEARCHING = "DO_SEARCHING"; 